tst-ieee754: tst-ieee754.o
	riscv64-unknown-linux-gnu-gcc -static -o tst-ieee754 tst-ieee754.c -L/home/handong/github/rocket-chip/riscv-tools/riscv-gnu-toolchain/build-glibc-linux64/math -lm

clean:
	rm *o tst-ieee754

