#!/bin/busybox ash

# Do your stuff here.
#echo "This script just mounts and boots the rootfs, nothing else!"
#echo "hello"
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t devtmpfs devtmpfs /dev
#boots up and runs executable and poweroffs!
/bin/busybox ash
#/bin/busybox ash ./r
